// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package_0402

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0402Client is the client API for Zhaoh0402 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0402Client interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0402Client struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0402Client(cc grpc.ClientConnInterface) Zhaoh0402Client {
	return &zhaoh0402Client{cc}
}

func (c *zhaoh0402Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0402.sample_package_0402.Zhaoh0402/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0402Server is the server API for Zhaoh0402 service.
// All implementations must embed UnimplementedZhaoh0402Server
// for forward compatibility
type Zhaoh0402Server interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0402Server()
}

// UnimplementedZhaoh0402Server must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0402Server struct {
}

func (UnimplementedZhaoh0402Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedZhaoh0402Server) mustEmbedUnimplementedZhaoh0402Server() {}

// UnsafeZhaoh0402Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0402Server will
// result in compilation errors.
type UnsafeZhaoh0402Server interface {
	mustEmbedUnimplementedZhaoh0402Server()
}

func RegisterZhaoh0402Server(s grpc.ServiceRegistrar, srv Zhaoh0402Server) {
	s.RegisterService(&Zhaoh0402_ServiceDesc, srv)
}

func _Zhaoh0402_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0402Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0402.sample_package_0402.Zhaoh0402/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0402Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0402_ServiceDesc is the grpc.ServiceDesc for Zhaoh0402 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0402_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0402.sample_package_0402.Zhaoh0402",
	HandlerType: (*Zhaoh0402Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Zhaoh0402_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Zhaoh0402.proto",
}
